version: "3"
services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres-shop
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./shared-files/database/postgresql:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: rabbit-mq-shop
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"

  redis:
    image: redis:alpine
    container_name: redis-shop
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: backend-shop
    entrypoint: ./entrypoint.sh
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/shop/app
      - ./.env:/usr/src/shop/.env
    env_file:
      .env
    depends_on:
      - rabbitmq
      - redis
      - db

  worker:
    build: .
    container_name: worker-shop
    entrypoint: ./entrypoint-celery.sh
    volumes:
      - ./app:/usr/src/shop/app
      - ./.env:/usr/src/shop/.env
    env_file:
      .env
    depends_on:
      - app
      - rabbitmq
      - redis

  dashboard:
    image: mher/flower:0.9.5
    container_name: dashboard-shop
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      FLOWER_PURGE_OFFLINE_WORKERS: "${FLOWER_PURGE_OFFLINE_WORKERS}"
    depends_on:
      - rabbitmq
      - redis

