version: "3"
services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres-shop
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./shared-files/database/postgresql:/var/lib/postgresql/data



  app:
    build: .
    container_name: backend-shop
    entrypoint: ./entrypoint.sh
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/shop/app
      - ./.env:/usr/src/shop/.env
    env_file:
      .env
    depends_on:
      - db

