"""Add index for cart for uid

Revision ID: 361e5ee8dbb3
Revises: c1dae807eb76
Create Date: 2021-11-01 07:19:47.138548

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "361e5ee8dbb3"
down_revision = "c1dae807eb76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_crt_cart_uid"), "crt_cart", ["uid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crt_cart_uid"), table_name="crt_cart")
    # ### end Alembic commands ###
