"""migration message

Revision ID: 20c4e84abf08
Revises: cfc24f602cf0
Create Date: 2021-11-08 07:23:34.236041

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20c4e84abf08"
down_revision = "cfc24f602cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "product_in_cart",
        "crt_cart_item",
        ["cart_id", "product_id"],
        unique=False,
    )
    op.add_column(
        "usr_token",
        sa.Column("_scope", postgresql.ARRAY(sa.VARCHAR()), nullable=True),
    )
    op.drop_column("usr_token", "scope")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usr_token",
        sa.Column(
            "scope",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("usr_token", "_scope")
    op.drop_index("product_in_cart", table_name="crt_cart_item")
    # ### end Alembic commands ###
