"""Change category model

Revision ID: 153cbc41a5e9
Revises: ae096c3e9f95
Create Date: 2021-10-27 18:32:22.328502

"""


# revision identifiers, used by Alembic.
revision = "153cbc41a5e9"
down_revision = "ae096c3e9f95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
