"""Update

Revision ID: cfc24f602cf0
Revises: beae73892da2
Create Date: 2021-11-01 14:18:50.011903

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfc24f602cf0"
down_revision = "beae73892da2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usr_token", sa.Column("expired_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usr_token", "expired_at")
    # ### end Alembic commands ###
