"""Added lazy load for categories

Revision ID: ae096c3e9f95
Revises: 41e4d6d5a19e
Create Date: 2021-10-25 14:32:48.065720

"""


# revision identifiers, used by Alembic.
revision = "ae096c3e9f95"
down_revision = "41e4d6d5a19e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
