"""Update

Revision ID: beae73892da2
Revises: 361e5ee8dbb3
Create Date: 2021-11-01 14:07:12.003216

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "beae73892da2"
down_revision = "361e5ee8dbb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usr_token", "_expired_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usr_token",
        sa.Column(
            "_expired_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
