"""Added role and scope models

Revision ID: 1339cec3c0a7
Revises: 7be45d612409
Create Date: 2021-11-09 12:15:15.199811

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1339cec3c0a7"
down_revision = "7be45d612409"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usr_role",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_usr_role_id"), "usr_role", ["id"], unique=False)
    op.create_table(
        "usr_scope",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_usr_scope_id"), "usr_scope", ["id"], unique=False)
    op.create_table(
        "Role_Scope",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("RoleId", sa.Integer(), nullable=True),
        sa.Column("ScopeId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["RoleId"],
            ["usr_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ScopeId"],
            ["usr_scope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Role_Scope")
    op.drop_index(op.f("ix_usr_scope_id"), table_name="usr_scope")
    op.drop_table("usr_scope")
    op.drop_index(op.f("ix_usr_role_id"), table_name="usr_role")
    op.drop_table("usr_role")
    # ### end Alembic commands ###
