"""migration message

Revision ID: 7be45d612409
Revises: 20c4e84abf08
Create Date: 2021-11-08 09:10:01.071257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7be45d612409"
down_revision = "20c4e84abf08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usr_token",
        sa.Column("scope", postgresql.ARRAY(sa.VARCHAR()), nullable=True),
    )
    op.drop_column("usr_token", "_scope")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usr_token",
        sa.Column(
            "_scope",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("usr_token", "scope")
    # ### end Alembic commands ###
