"""Added user email uniqe

Revision ID: 41e4d6d5a19e
Revises: d16dbbe02a4f
Create Date: 2021-10-24 21:10:06.859328

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "41e4d6d5a19e"
down_revision = "d16dbbe02a4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "usr_user", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usr_user", type_="unique")
    # ### end Alembic commands ###
